"""Added teacher, paper, course, project and their relationships

Revision ID: a7665fa6cf7d
Revises: 
Create Date: 2024-06-21 21:19:30.423434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7665fa6cf7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('nature', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Date(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('total_funding', sa.Float(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('title', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_course',
    sa.Column('teacher_id', sa.String(length=5), nullable=False),
    sa.Column('course_id', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('hours_taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'course_id')
    )
    op.create_table('teacher_paper',
    sa.Column('teacher_id', sa.String(length=5), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_corresponding_author', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'paper_id')
    )
    op.create_table('teacher_project',
    sa.Column('teacher_id', sa.String(length=5), nullable=False),
    sa.Column('project_id', sa.String(length=256), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('funding_taken', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_project')
    op.drop_table('teacher_paper')
    op.drop_table('teacher_course')
    op.drop_table('teacher')
    op.drop_table('project')
    op.drop_table('paper')
    op.drop_table('course')
    # ### end Alembic commands ###
